module.exports={
    dynamicTablePageURL: "http://uitestingplayground.com/dynamictable",
    verifyTextPageURL: "http://uitestingplayground.com/verifytext",
    progressBarPageURL: "http://uitestingplayground.com/progressbar",
    visibilityPageURL: "http://uitestingplayground.com/visibility",
    sampleAppPageURL: "http://uitestingplayground.com/sampleapp",
    shadowdomPageURL: "http://uitestingplayground.com/shadowdom",
    dynamicIDPageURL: "http://uitestingplayground.com/dynamicid",
    classAttributePageURL: "http://uitestingplayground.com/classattr",
    hiddenLayerPageURL: "http://uitestingplayground.com/hiddenlayers",
    mouseoverPageURL: "http://uitestingplayground.com/mouseover",
    clientDelayPageURL: "http://uitestingplayground.com/clientdelay",
    clickPageURL: "http://uitestingplayground.com/click",
    textInputPageURL: "http://uitestingplayground.com/textinput",
    scrollbarsPageURL: "http://uitestingplayground.com/scrollbars",
    nbspPageURL: "http://uitestingplayground.com/nbsp",
    overlappedPageURL: "http://uitestingplayground.com/overlapped",
    loadDelayPageURL: "http://uitestingplayground.com/loaddelay",
    ajaxDataPageURL: "http://uitestingplayground.com/ajax"
}