my_access_key = "AKIA4RMNGMRIPKFYRSVT"
my_secret_key = "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"
region        = "us-west-2"
origin_id     = "web-wbd-tcoe"
s3_endpoint   = "web-wbd-tcoe.s3.amazonaws.com/index.html"
